### ISSUE TITLE
KristPay loop between 2 servers

### ISSUE THREAD

**Issue by Ale32bit** [Lemmmy/KristPay2#2]
I tried sending from SC to my server name some krists without meta and it caused a loop between the 2 servers trying to send the krists back because `donate=true` was not specified in the meta, this caused Krist to be down for a few seconds (DOS).
To stop the DOS I had to restart my server.

**Comment by Wojbie** [comment]
The issue seems to be partially cause kristpay when returning wrong message is not following `return=` commonmeta and just returning to address instead.

I would suggest following return commonmeta and include some additional counter in commonmeta that would get increased every error and would cause kristpay to treat message as donate=true after it exceeded. Like errorcount=5

**Comment by BTCTaras** [comment]
Alternatively, treat all direct payments with no username specified as a donation, and only return mistyped usernames

**Comment by Wojbie** [comment]
Even then if direct payment has return= value it would be a good idea to follow it.. I realize that could be used to loop but it would allow for mistyped cross server payments to be returned properly instead of getting wiped.
